### ISSUE TITLE
 Should ego-tree be reexported by this crate?

### ISSUE THREAD

**Issue by Samuel-Martineau** [rust-scraper/scraper#208]
Hi,

I was playing around with this library (amazing work, by the way), but I am running into issues with `ego-tree` version mismatch.

To traverse the DOM tree, it seems natural to me to use recursion. Consider something like the following, which prints the HTML tags with increasing indentation:
```rust
fn traverse(node: NodeRef<Node>, depth: usize) {
    match node.value() {
        Node::Element(e) => {
            println!("{}{e:#?}", " ".repeat(depth));
            for child in node.children() {
                traverse(child, depth + 1);
            }
        },
        _ => {
            if let Some(child) = node.first_child() {
                traverse(child, depth);
            }
        }
    }
}
```

Unfortunately, this approach requires the use of `NodeRef` from `ego-tree`. Currently, it doesn't seem like this is reexported from `scraper`, which means `ego-tree` needs to be separately installed, and that the version of the crate must be managed manually?

Am I doing something incredibly unidiomatic here? If so, I apologize for my incompetence. If not, would you consider reexporting `ego-tree`, or at the very least, the core structs like `NodeRef`?

**Comment by Rolv-Apneseth** [comment]
Hey, thanks for the making this crate, trying to use it for the first time at the moment.

I came here to open the same issue though.

Since types from `ego-tree` are directly returned by method calls from this crate, I would also have expected it to be re-exported, or at least have the types that _are_ used by this crate re-exported. This would avoid forcing users to manually import it and manage version mismatches.
